<%@ Page Language="C#" AutoEventWireup="true" CodeFile="StudentDataHandlingByUsingGrid.aspx.cs" Inherits="StudentDta" %>

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head id="Head1" runat="server">
    <title>Student Data Management</title>
    <style>
        body {
            font-family: 'Segoe UI', sans-serif;
            background: linear-gradient(135deg, #a8edea, #fed6e3);
            margin: 0;
            padding: 20px;
        }

        h1 {
            text-align: center;
            color: #444;
            background: #fff3cd;
            padding: 15px;
            border-radius: 10px;
            margin-bottom: 20px;
        }

        .grid-container {
            background: white;
            padding: 20px;
            border-radius: 12px;
            box-shadow: 0px 6px 15px rgba(0,0,0,0.15);
        }

        .grid-container .aspNet-GridView {
            border-collapse: collapse;
            width: 100%;
            overflow-x: auto;
        }

        /* Header Row */
        .grid-container .aspNet-GridView th {
            background-color: #ff6f61;
            color: white;
            padding: 10px;
            font-size: 16px;
        }

        /* Data Rows */
        .grid-container .aspNet-GridView td {
            padding: 8px;
            text-align: center;
            border-bottom: 1px solid #ddd;
        }

        /* Alternate row colors */
        .grid-container .aspNet-GridView tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .grid-container .aspNet-GridView tr:nth-child(odd) {
            background-color: #fff;
        }

        /* Hover effect */
        .grid-container .aspNet-GridView tr:hover {
            background-color: #ffe5b4;
            cursor: pointer;
        }

        /* Buttons */
        .grid-container a {
            background: #28a745;
            color: white;
            padding: 5px 10px;
            text-decoration: none;
            border-radius: 5px;
            font-size: 14px;
        }
        .grid-container a:hover {
            background: #218838;
        }

        /* Delete button */
        .grid-container a[id*="DeleteButton"] {
            background: #dc3545;
        }
        .grid-container a[id*="DeleteButton"]:hover {
            background: #c82333;
        }
    </style>
</head>
<body>
    <form id="form1" runat="server">
        <h1>🎓 Student Data Management</h1>
        <div class="grid-container">
            <asp:GridView ID="GridView1" runat="server" CssClass="aspNet-GridView"
                AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" 
                DataKeyNames="id" DataSourceID="SqlDataSource1">
                <Columns>
                    <asp:BoundField DataField="id" HeaderText="ID" ReadOnly="True" SortExpression="id" />
                    <asp:BoundField DataField="name" HeaderText="Name" SortExpression="name" />
                    <asp:BoundField DataField="fatherName" HeaderText="Father Name" SortExpression="fatherName" />
                    <asp:BoundField DataField="DateOfBirth" HeaderText="Date of Birth" SortExpression="DateOfBirth" />
                    <asp:BoundField DataField="Department" HeaderText="Department" SortExpression="Department" />
                    <asp:BoundField DataField="year" HeaderText="Year" SortExpression="year" />
                </Columns>
            </asp:GridView>

            <asp:SqlDataSource ID="SqlDataSource1" runat="server" 
                ConnectionString="<%$ ConnectionStrings:ConnectionString %>" 
                SelectCommand="SELECT [id], [name], [fatherName], [DateOfBirth], [Department], [year] FROM [StudentData]"  
                UpdateCommand="UPDATE [StudentData] SET [name]=@name,[fatherName]=@fatherName,[DateOfBirth]=@DateOfBirth,[Department]=@Department,[year]=@year WHERE [id]=@id"  
                DeleteCommand="DELETE FROM StudentData WHERE [id]=@id">
            </asp:SqlDataSource>
        </div>
    </form>
</body>
</html>
